pipeline:

  build:
    image: golang:latest
    pull: true
    secrets:
      - MY_K8S_TOKEN
    environment:
      - AAAAA=glacon
    commands:
    - GOPATH=`pwd`/.env go build -o test
    - ./test
    - env | sort
    - sleep 60
    when:
      event: [push, tag]
