kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: clone
  pull: default
  image: plugins/git
  settings:
    tags: true

- name: build
  pull: always
  image: alpine/git
  commands:
  - "env | sort"
  - git tag
  - ls -l /data
  - sleep 60
  environment:
    AAAAA: glacon
    MY_K8S_TOKEN:
      from_secret: MY_K8S_TOKEN
  volumes:
  - name: 2f686f6d652f6775696c6c61756d655f736d616861
    path: /data
  when:
    event:
    - push
    - tag

volumes:
- name: 2f686f6d652f6775696c6c61756d655f736d616861
  host:
    path: /home/guillaume_smaha
