kind: pipeline
name: default

steps:
- name: simple
  commands:
    - "env | sort"
    - "git tag"
    - "ls -l /data"
    - "sleep 10"
  environment:
    - AAAAA=glacon
  image: alpine/git
  pull: true
  secrets:
    - MY_K8S_TOKEN
  volumes:
    - /home/guillaume_smaha:/data
  when:
    event:
      - push
      - tag

  # "Build my case (GPU)":
  #   commands:
  #     - "env | sort"
  #     - "git tag"
  #     - "ls -l /data"
  #     - "sleep 10"
  #   environment:
  #     - AAAAA=glacon
  #   image: alpine/git
  #   pull: true
  #   secrets:
  #     - MY_K8S_TOKEN
  #   volumes:
  #     - /home/guillaume_smaha:/data
  #   when:
  #     event:
  #       - push
  #       - tag
   
  # "build(":
  #   commands:
  #     - "env | sort"
  #     - "git tag"
  #     - "ls -l /data"
  #     - "sleep 10"
  #   environment:
  #     - AAAAA=glacon
  #   image: alpine/git
  #   pull: true
  #   secrets:
  #     - MY_K8S_TOKEN
  #   volumes:
  #     - /home/guillaume_smaha:/data
  #   when:
  #     event:
  #       - push
  #       - tag

   
  # "build_":
  #   commands:
  #     - "env | sort"
  #     - "git tag"
  #     - "ls -l /data"
  #     - "sleep 10"
  #   environment:
  #     - AAAAA=glacon
  #   image: alpine/git
  #   pull: true
  #   secrets:
  #     - MY_K8S_TOKEN
  #   volumes:
  #     - /home/guillaume_smaha:/data
  #   when:
  #     event:
  #       - push
  #       - tag

