pipeline:

  build:
    image: golang:latest
    pull: true
    environment:
      AAAAA=glacon
    commands:
    - GOPATH=`pwd`/.env go build -o test
    - ./test
    - env | sort
    - sleep 300
    when:
      event: [push, tag]

