docker_info: &docker_info
  name: docker information
  image: alpine:3.7
  commands:
    - set
    - env | sort

pipeline:

  info:
    <<: *docker_info

  build:
    image: alpine/git
    pull: true
    commands:
      - "env | sort"
      - "git tag"
      - "ls -l /data"
      - "sleep 10"
    when:
      event: [push, tag]
