clone: 
  image: plugins/git
  tags: true
pipeline: 
  build: 
    commands: 
      - "env | sort"
      - "git tag"
      - "sleep 60"
    environment: 
      - AAAAA=glacon
    image: alpine/git
    pull: true
    secrets: 
      - MY_K8S_TOKEN
    when: 
      event: 
        - push
        - tag
