
clone:
  image: plugins/git
  tags: true

pipeline:

  build:
    image: alpine/git
    pull: true
    secrets:
      - MY_K8S_TOKEN
    environment:
      - AAAAA=glacon
    commands:
    - env | sort
    - git tag
    - sleep 60
    when:
      event: [push, tag]
