
clone:
  clone:
    image: plugins/git
    disable: true

pipeline:
  clone:
    image: plugins/git
    tags: true
   
  build: 
    commands: 
      - "env | sort"
      - "git tag"
      - "ls -l /data"
      - "sleep 10"
    environment: 
      - AAAAA=glacon
    image: alpine/git
    pull: true
    secrets: 
      - MY_K8S_TOKEN
    volumes:
      - /home/guillaume_smaha:/data
    when: 
      event: 
        - push
        - tag

  build2: 
    commands: 
      - "env | sort"
      - "git tag"
      - "ls -l /data"
      - "sleep 10"
    environment: 
      - AAAAA=glacon
    image: alpine/git
    pull: true
    secrets: 
      - MY_K8S_TOKEN
    volumes:
      - /home/guillaume_smaha:/data
    when: 
      event: 
        - push
        - tag

